/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.train.packs;

import com.formdev.flatlaf.FlatDarkLaf;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
/**
 *
 * @author HP
 */
public class AEDTrain extends javax.swing.JFrame {
    
    
    public String name;   
    public AEDTrain(String uname) {
        initComponents();
        name=uname;
    }

    private AEDTrain() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    class node{
        node next;
        node prev;
        String data;
        public node(String data)
        {
            this.data=data;
            next=prev=null;
        }
        
    }
    class DLL{
        node head;
        node tail;
        public DLL()
        {
            head=null;
            tail=null;
        }
        public void insert(String value)
        {
            node n=new node(value);
            if(head==null)
            {
                head=n;
                tail=n;
            }
            else 
            {
                tail.next=n;
                n.prev=tail;
                tail=n;
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time1 = new cambodia.raven.Time();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jfrom = new javax.swing.JComboBox<>();
        jname = new javax.swing.JComboBox<>();
        jto = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        idtext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        time1.setBackground(new java.awt.Color(153, 153, 153));
        time1.setTextRefernce(jtime);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTable1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TrainID", "Train Name", "From", "To", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 940, 280));

        jfrom.setForeground(new java.awt.Color(255, 255, 255));
        jfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sukkur", "Quetta", "Hyderabad" }));
        jfrom.setBorder(null);
        jfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfromActionPerformed(evt);
            }
        });
        getContentPane().add(jfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 150, 40));

        jname.setForeground(new java.awt.Color(255, 255, 255));
        jname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BulletTrain", "GoldenArrow", "PheonixExpress", "Khyber Mail", "Green Line Express", "Awam Express", "Tezgam", "Karakoram Express", "Allama Iqbal Express", "Pak Business Express", "Shalimar Express", "Bolan Mail", "Sukkur Express" }));
        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 150, 40));

        jto.setForeground(new java.awt.Color(255, 255, 255));
        jto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islamabad", "Karachi", "Lahore" }));
        jto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtoActionPerformed(evt);
            }
        });
        getContentPane().add(jto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 150, 40));

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 110, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 51));
        jLabel7.setText("  Train Captain");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 3));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 180, 40));

        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 110, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("To");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Time");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("From");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Train Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtimeActionPerformed(evt);
            }
        });
        getContentPane().add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 130, 40));
        jtime.getAccessibleContext().setAccessibleName("");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 20, 40));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel8.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BACK");
        jLabel8.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Red"), 3, true));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 110, 40));

        dateChooserCombo1.setCalendarBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 150, 40));

        idtext.setEditable(false);
        idtext.setForeground(new java.awt.Color(255, 255, 255));
        idtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtextActionPerformed(evt);
            }
        });
        getContentPane().add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Train ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel10.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SAVE");
        jLabel10.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Green"), 3, true));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 110, 40));

        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("VIEW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/wallpaperbetter.com_1440x900.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel11.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SAVE");
        jLabel11.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Green"), 3, true));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 110, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfromActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void jtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtoActionPerformed
String Dupl[];
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
String jid = idtext.getText().toString();
String tn = jname.getSelectedItem().toString();
String jf = jfrom.getSelectedItem().toString();
String jt = jto.getSelectedItem().toString();
String jm = jtime.getText();
String jd = dateChooserCombo1.getText();

// ...
if (jm.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please specify a Time...");
} else if (jd.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please specify a Date...");
} else {
    try {
        Connection con = SConnection.getcon();
        
        // Check if the train with the same name exists on the same date
        String checkQuery = "SELECT * FROM train WHERE TrainName = ? AND Date = ?";
        PreparedStatement checkPs = con.prepareStatement(checkQuery);
        checkPs.setString(1, tn);
        checkPs.setString(2, jd);
        ResultSet checkRs = checkPs.executeQuery();

        if (checkRs.next()) {
            // Train with the same name exists on the same date, prompt for updating the date
            int option = JOptionPane.showConfirmDialog(null, "Train with the same Name already exists on the same Date. Do you want to update the date?", "Duplicate Train", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Update the date here
                String updateQuery = "UPDATE train SET Date = ? WHERE TrainName = ? AND Date = ?";
                PreparedStatement updatePs = con.prepareStatement(updateQuery);
                updatePs.setString(1, jd);
                updatePs.setString(2, tn);
                updatePs.setString(3, jd);
                updatePs.executeUpdate();
            } else {
                // Exit without adding the train
                return;
            }
        } else {
            // Train with the same name and date doesn't exist, add it to the table
            String insertQuery = "INSERT INTO train (TrainID, TrainName, `From`, `To`, Time, Date) " +
                                 "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement insertPs = con.prepareStatement(insertQuery);
            insertPs.setString(1, jid);
            insertPs.setString(2, tn);
            insertPs.setString(3, jf);
            insertPs.setString(4, jt);
            insertPs.setString(5, jm);
            insertPs.setString(6, jd);
            insertPs.executeUpdate();

            String Data[] = {jid, tn, jf, jt, jm, jd};
            dt.addRow(Data);

            FileWriter f1 = new FileWriter("C:\\Users\\karan\\Documents\\NetBeansProjects\\DSA Project\\TrainProject\\TrainRecords\\" + jid + ".txt");
            f1.write("    " + jid + "     " + tn + "     " + jf + "     " + "jt" + "     " + jm + "    " + jd + "\n");

            f1.write(System.getProperty("line.separator"));
            f1.close();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e);
    }
}
// ...


    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectionModel().isSelectionEmpty())
        {
        JOptionPane.showMessageDialog(null, "Select a Row First...");
        }
        else{ 
        Connection con=SConnection.getcon();           
        int row = jTable1.getSelectedRow();
        String eve = jTable1.getModel().getValueAt(row, 0).toString();

        String delRow = "delete from train where TrainID="+eve;
        try {
           PreparedStatement ps = con.prepareStatement(delRow);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Deleted Succesfully...");
                 try
                 {    
        ps = con.prepareStatement("Select * from train");
        ResultSet rs=ps.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        tm.setRowCount(0);
        while(rs.next()){
            Object o[] = {rs.getString("TrainID"),rs.getString("TrainName"),rs.getString("From"),rs.getString("To"),rs.getString("Time"),rs.getString("Date")};
            tm.addRow(o);
        }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"An Error Occured");
    }       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,  "Error 666");
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtimeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        time1.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
          if(name.equals("user"))
        {
      Menu  m =new Menu("user");
        m.setVisible(true);
        dispose();
        }
        else if(name.equals("jubli")){
        Menu  m =new Menu("jubli");
        m.setVisible(true);
        dispose();}
             else if(name.equals("arjun")){
        Menu  m =new Menu("arjun");
        m.setVisible(true);
        dispose();}
        else if(name.equals("anjle")){
        Menu  m =new Menu("anjle");
        m.setVisible(true);
        dispose();}
        else if(name.equals("aman")){
        Menu  m =new Menu("aman");
        m.setVisible(true);
        dispose();}
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         String filePath = "C:\\Users\\karan\\Downloads\\OOP FINAL PROJECT\\OOP FINAL PROJECT\\records.txt";
         if(jTable1.getRowCount()==0)
            {
                                JOptionPane.showMessageDialog(null,"No Data Inserted");
            }
         else
         {
         try {
           
            FileWriter fw = new FileWriter(filePath);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < jTable1.getRowCount(); i++){//rows
                for(int j = 0; j < jTable1.getColumnCount(); j++){//columns
                    bw.write(jTable1.getValueAt(i, j).toString()+"  ");
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            JOptionPane.showMessageDialog(null,"Data Succefully Saved");
                 if(name.equals("user"))
        {
      Menu  m =new Menu("user");
        m.setVisible(true);
        dispose();
        }
        else if(name.equals("jubli")){
        Menu  m =new Menu("jubli");
        m.setVisible(true);
        dispose();}
             else if(name.equals("arjun")){
        Menu  m =new Menu("arjun");
        m.setVisible(true);
        dispose();}
        else if(name.equals("anjle")){
        Menu  m =new Menu("anjle");
        m.setVisible(true);
        dispose();}
        else if(name.equals("aman")){
        Menu  m =new Menu("aman");
        m.setVisible(true);
        dispose();}
            

            
        } catch (Exception e) {
                               JOptionPane.showMessageDialog(null,"No Data Inserted");

        }}
    
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           try{
            Connection con=SConnection.getcon();
            Statement st=con.createStatement();
             CallableStatement cs = con.prepareCall("{CALL latest_train_id(?)}");
             cs.registerOutParameter(1, java.sql.Types.INTEGER);
             cs.execute();

            int result = cs.getInt(1);

           // Display the retrieved value in a text field
            idtext.setText(Integer.toString(result));

            PreparedStatement ps = (PreparedStatement) con.prepareStatement("Select * from train");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);

            while(rs.next()){

                Object o[] = {rs.getString("TrainID"),rs.getString("TrainName"),rs.getString("From"),rs.getString("To"),rs.getString("Time"),rs.getString("Date")};
                tm.addRow(o);

            }

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Employee  em =new Employee();
        em.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void idtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
  

        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
    UIManager.setLookAndFeel( new FlatDarkLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AEDTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JTextField idtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jfrom;
    private javax.swing.JComboBox<String> jname;
    private javax.swing.JTextField jtime;
    private javax.swing.JComboBox<String> jto;
    private cambodia.raven.Time time1;
    // End of variables declaration//GEN-END:variables
}
