/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.train.packs;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author HP
 */
public class AddTicket extends javax.swing.JFrame {

    /**
     * Creates new form AddTicket
     */
    String name;
    public AddTicket(String uname) {
        initComponents();
        name=uname;
    }

    private AddTicket() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    class node{
        node next;
        node prev;
        String data;
        public node(String data)
        {
            this.data=data;
            next=prev=null;
        }
        
    }
    class DLL{
        node head;
        node tail;
        public DLL()
        {
            head=null;
            tail=null;
        }
        public void insert(String value)
        {
            node n=new node(value);
            if(head==null)
            {
                head=n;
                tail=n;
            }
            else 
            {
                tail.next=n;
                n.prev=tail;
                tail=n;
            }
        }
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tickettext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Your Name:");

        tickettext.setEditable(false);
        tickettext.setToolTipText("");
        tickettext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickettextActionPerformed(evt);
            }
        });
        tickettext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tickettextKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Class:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Business Class");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Economy CLass");

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(8);
        jSlider1.setMinimum(1);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Quantity:");

        jButton2.setBackground(new java.awt.Color(60, 63, 65));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Red"), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(60, 63, 65));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Green"), 3, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Ticket ID");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/Food_Text_Effect 1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 3));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOK TICKET");

        jScrollPane3.setBorder(null);

        jTable2.setBackground(new java.awt.Color(102, 102, 102));
        jTable2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jTable2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jTable2.setForeground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TrainID", "Train Name", "From", "To", "Time", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setFocusable(false);
        jTable2.setShowGrid(true);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("TrainID");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Train Name");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("From");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("To");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Time");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Date");
        }

        jButton8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("VIEW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(60, 63, 65));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 204, 0));
        jButton4.setText("Boarding Pass");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tickettext, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addGap(88, 88, 88)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickettext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel8)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 600));

        tarea.setEditable(false);
        tarea.setColumns(20);
        tarea.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tarea.setRows(5);
        tarea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "YOUR TICKET", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT Condensed", 0, 18))); // NOI18N
        jScrollPane1.setViewportView(tarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 360, 430));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PRINT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 360, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/bg10.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(500, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 430, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String tclass="";
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
                printRecord(tarea);
        
               







    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        // Assuming you have a connection class named SConnection
        

// Use the 'con' connection object to perform further database operations
// For example, you can execute SQL queries using this connectio

    // Use the variables as needed
    // ...}

        
        
        String tid   = tickettext.getText();
        String yname = jTextField2.getText();
        int qty = jSlider1.getValue();
        int price=0;
        int tax=10;

        if(jRadioButton1.isSelected())
        {
            tclass="Business";
            price=200;
        }
        else if(jRadioButton2.isSelected())
        {
            tclass = "Economy";
            price=120;
        }
        if(tid.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ID Should Not Be empty");
        }
         else if(tclass=="")
        {
            JOptionPane.showMessageDialog(null,"Please Select a Class");
        }
         else if(yname=="")
         {
             JOptionPane.showMessageDialog(null,"Please Enter Name ");
         }

        else{
             if(jTable2.getSelectionModel().isSelectionEmpty())
        {
        JOptionPane.showMessageDialog(null, "Select a Row First...");
        }
        else{ 
            try
            {
                Connection con = SConnection.getcon();
                int row = jTable2.getSelectedRow();
                String id = jTable2.getModel().getValueAt(row, 0).toString();
                String tname = jTable2.getModel().getValueAt(row, 1).toString();
                String tfrom = jTable2.getModel().getValueAt(row, 2).toString();
                String tto = jTable2.getModel().getValueAt(row, 3).toString();
                String tdate = jTable2.getModel().getValueAt(row, 4).toString();
                String ttime = jTable2.getModel().getValueAt(row, 5).toString();
                Statement st=con.createStatement();
                st.executeUpdate("Insert into ticket values('"+tid+"','"+yname+"','"+id+"','"+tname+"','"+tclass+"','"+qty+"','"+tfrom+"','"+tto+"','"+ttime+"','"+tdate+"')");

                tarea.setText ("-------------------------------------------------\n");
                tarea.append ("\tJ.A.R.S Railway Reservation\n");
                tarea.append ("-------------------------------------------------\n\n\n");
                tarea.append ("TICKET ID\t\t"+":"+tid);
                tarea.append ("\nTICKET NAME\t\t"+":"+yname);
                tarea.append ("\nTRAIN NAME\t\t"+":"+tname);
                tarea.append ("\nFROM\t\t"+":"+tfrom);
                tarea.append ("\nTO\t\t"+":"+tto);
                tarea.append ("\nCLASS\t\t"+":"+tclass);
                tarea.append ("\nQUANTITY\t\t"+":"+qty);
                tarea.append ("\n\n\n\n-------------------------------------------------");
                tarea.append ("\nSUB-TOTAL\t\t\t"+": $"+(qty*price));
                tarea.append ("\nTAX\t\t\t"+": $"+qty*tax);
                tarea.append ("\nTOTAL\t\t\t"+": $"+((qty*price)+(qty*tax)));
                int total=(qty*price)+(qty*tax);
                tarea.append ("\n-------------------------------------------------");
                JOptionPane.showMessageDialog(null,"Ticket Generated Successfully...");
                tickettext.setText("");
                jTextField2.setText("");

                FileWriter f1=new FileWriter("C:\\Users\\karan\\Documents\\NetBeansProjects\\DSA Project\\TrainProject\\TicketRecords\\"+tid+".txt");
                    f1.write("-------------------------------------------------\n"+"\tJ.A.R.S Railway Reservation\n"+
                        "-------------------------------------------------\n\n\n"+ "TICKET ID\t\t"+":"+tid+"\nTICKET NAME\t\t"+":"+yname+
                        "\nTRAIN NAME\t\t"+":"+tname+ "\nFROM\t\t"+":"+tfrom+"\nTO\t\t"+":"+tto+
                        "\nCLASS\t\t"+":"+tclass+"\nQUANTITY\t\t"+":"+qty+
                        "\n\n\n\n-------------------------------------------------"+"\nTOTAL\t\t\t"+": $"+total);

                    f1.write(System.getProperty("line.separator"));
                    f1.close();
                    DLL d=new DLL();
                    d.insert(tid);

                }

                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"TicketID Already Exists...");
                }
            }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(name.equals("user"))
        {
            Menu  m =new Menu("user");
            m.setVisible(true);
            dispose();
        }
        else if(name.equals("jubli")){
            Menu  m =new Menu("jubli");
            m.setVisible(true);
            dispose();}
        else if(name.equals("arjun")){
            Menu  m =new Menu("arjun");
            m.setVisible(true);
            dispose();}
        else if(name.equals("anjle")){
            Menu  m =new Menu("anjle");
            m.setVisible(true);
            dispose();}
        else if(name.equals("aman")){
            Menu  m =new Menu("aman");
            m.setVisible(true);
            dispose();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void tickettextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tickettextKeyTyped

        tickettext.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_tickettextKeyTyped

    private void tickettextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickettextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tickettextActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con=SConnection.getcon();
            Statement st=con.createStatement();
             CallableStatement cs = con.prepareCall("{CALL latest_ticket_id(?)}");
             cs.registerOutParameter(1, java.sql.Types.INTEGER);
             cs.execute();

            int result = cs.getInt(1);

           // Display the retrieved value in a text field
            tickettext.setText(Integer.toString(result));

            PreparedStatement ps = (PreparedStatement) con.prepareStatement("Select * from train");
            ResultSet rs=ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
            tm.setRowCount(0);

            while(rs.next()){

                Object o[] = {rs.getString("TrainID"),rs.getString("TrainName"),rs.getString("From"),rs.getString("To"),rs.getString("Time"),rs.getString("Date")};
                tm.addRow(o);

            }

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        View_Boarding_Pass  b =new View_Boarding_Pass();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Food_Menu  f =new Food_Menu();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea tarea;
    private javax.swing.JTextField tickettext;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JTextArea tarea) {
        PrinterJob pj = PrinterJob.getPrinterJob();
        
        pj.setJobName("Print Record");
        pj.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pf,int pageIndex) throws PrinterException {
            if(pageIndex > 0){
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D graphics2d = (Graphics2D)graphics;
            graphics2d.translate(pf.getImageableX()*2,pf.getImageableY()*2);
           graphics2d.scale(0.5,0.5);
           tarea.paint(graphics2d);
           
           return Printable.PAGE_EXISTS;
            }
            });
        boolean result= pj.printDialog();
        if (result)
        {
            try
            {
                pj.print();
            
            }
            catch(PrinterException printerException)
            {
            JOptionPane.showMessageDialog(this, "Print Error: "+printerException.getMessage());
            }
        
        }
        
    }
}
