/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.train.packs;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.TextField;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author karan
 */
public class View_Boarding_Pass extends javax.swing.JFrame {

    /**
     * Creates new form View_Boarding_Pass
     */
    public View_Boarding_Pass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pto = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        pfrom2 = new javax.swing.JTextField();
        pdate = new javax.swing.JTextField();
        pquantity = new javax.swing.JTextField();
        pclass = new javax.swing.JTextField();
        ptime = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        tclass = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        pfrom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("                                          Boarding Pass");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1685, 63));

        pto.setBackground(new java.awt.Color(235, 235, 235));
        pto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptoActionPerformed(evt);
            }
        });
        jPanel1.add(pto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 120, 25));

        from.setBackground(new java.awt.Color(235, 235, 235));
        from.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        jPanel1.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, 25));

        quantity.setBackground(new java.awt.Color(235, 235, 235));
        quantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, 25));

        date.setBackground(new java.awt.Color(235, 235, 235));
        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 150, 27));

        pfrom2.setBackground(new java.awt.Color(235, 235, 235));
        pfrom2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pfrom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfrom2ActionPerformed(evt);
            }
        });
        jPanel1.add(pfrom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 110, 31));

        pdate.setBackground(new java.awt.Color(235, 235, 235));
        pdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdateActionPerformed(evt);
            }
        });
        jPanel1.add(pdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 70, 31));

        pquantity.setBackground(new java.awt.Color(235, 235, 235));
        pquantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pquantityActionPerformed(evt);
            }
        });
        jPanel1.add(pquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 79, 40));

        pclass.setBackground(new java.awt.Color(235, 235, 235));
        pclass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pclassActionPerformed(evt);
            }
        });
        jPanel1.add(pclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 150, 40));

        ptime.setBackground(new java.awt.Color(235, 235, 235));
        ptime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ptime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptimeActionPerformed(evt);
            }
        });
        jPanel1.add(ptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 79, 40));

        time.setBackground(new java.awt.Color(235, 235, 235));
        time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 50, 25));

        name1.setBackground(new java.awt.Color(235, 235, 235));
        name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, 25));

        to.setBackground(new java.awt.Color(235, 235, 235));
        to.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        jPanel1.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, 25));

        tclass.setBackground(new java.awt.Color(235, 235, 235));
        tclass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tclassActionPerformed(evt);
            }
        });
        jPanel1.add(tclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 150, 25));

        pname.setBackground(new java.awt.Color(235, 235, 235));
        pname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 120, 27));

        pfrom.setBackground(new java.awt.Color(235, 235, 235));
        pfrom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfromActionPerformed(evt);
            }
        });
        jPanel1.add(pfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, 27));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/board.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 806, 369));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("   Back");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 110, 40));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Ticket ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 90, 40));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("   View");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 110, 40));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("   Print");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 3));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptoActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void pfrom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfrom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfrom2ActionPerformed

    private void pdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdateActionPerformed

    private void pquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pquantityActionPerformed

    private void pclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pclassActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void tclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tclassActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void pfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfromActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         AddTicket  a =new AddTicket("jubli");
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        printRecord(jLabel1);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String T_id = jTextField1.getText();
        if(T_id.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"ID Should Not Be empty");
        }
        else {
             
            try {
                Connection con=SConnection.getcon();
                Statement st=con.createStatement();
            

            CallableStatement cs = con.prepareCall("{CALL board("+T_id+",?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");

// Registering output parameters for each attribute
cs.registerOutParameter(1, java.sql.Types.VARCHAR);  // Attribute 1
cs.registerOutParameter(2, java.sql.Types.VARCHAR);  // Attribute 2
cs.registerOutParameter(3, java.sql.Types.VARCHAR);  // Attribute 3
cs.registerOutParameter(4, java.sql.Types.VARCHAR);  // Attribute 4
cs.registerOutParameter(5, java.sql.Types.VARCHAR);  // Attribute 5
cs.registerOutParameter(6, java.sql.Types.VARCHAR);  // Attribute 6
cs.registerOutParameter(7, java.sql.Types.VARCHAR);  // Attribute 7
cs.registerOutParameter(8, java.sql.Types.VARCHAR);  // Attribute 8
cs.registerOutParameter(9, java.sql.Types.VARCHAR);  // Attribute 9
cs.registerOutParameter(10, java.sql.Types.VARCHAR); // Attribute 10


cs.execute();

// Retrieving values for each attribute
String id = cs.getString(1);   // Attribute 1
String ticketname = cs.getString(2);   // Attribute 2
String trainid = cs.getString(3);   // Attribute 3
String trainname = cs.getString(4);   // Attribute 4
String tclasser = cs.getString(5);   // Attribute 5
String quantityy = cs.getString(6);   // Attribute 6
String fro = cs.getString(7);   // Attribute 7
String too = cs.getString(8);   // Attribute 8
String timer = cs.getString(9);   // Attribute 9
String dater = cs.getString(10); // Attribute 10
/*
SELECT t_id into A  FROM ticket where t_id = id ;
SELECT t_name into B FROM ticket where t_id = id ;
SELECT TrainID into C FROM ticket where t_id = id ; 
SELECT TrainName into D FROM ticket where t_id = id ;
SELECT class into E FROM ticket where t_id = id ;
SELECT quantity into F FROM ticket where t_id = id ;
SELECT fro into G FROM ticket where t_id = id ;
SELECT too into H FROM ticket where t_id = id ;
SELECT time into I FROM ticket where t_id = id ;
SELECT date into J FROM ticket where t_id = id ;*/


name1.setText( 
        "" + trainname );
tclass.setText( 
        "" + tclasser );
quantity.setText( 
        "" + quantityy );
from.setText( 
        "" + fro );
to.setText( 
        "" + too );
time.setText( 
        "" + dater );
date.setText( 
        "" + timer );
pname.setText( 
        "" + ticketname );
pfrom.setText( 
        "" + fro );
pto.setText( 
        "" + too );
pclass.setText( 
        "" + tclasser );
ptime.setText( 
        "" + dater );
pdate.setText( 
        "" + timer );
pquantity.setText( 
        "" + quantityy );
pfrom2.setText( 
        "" + fro );

        }
            
            catch (SQLException ex) {
                Logger.getLogger(View_Boarding_Pass.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jLabel5MouseClicked

    private void ptimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Boarding_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Boarding_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Boarding_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Boarding_Pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Boarding_Pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField pclass;
    private javax.swing.JTextField pdate;
    private javax.swing.JTextField pfrom;
    private javax.swing.JTextField pfrom2;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pquantity;
    private javax.swing.JTextField ptime;
    private javax.swing.JTextField pto;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField tclass;
    private javax.swing.JTextField time;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
private void printRecord(JLabel jLabel1) {
    PrinterJob pj = PrinterJob.getPrinterJob();
    
    pj.setJobName("Print Record");
    pj.setPrintable(new Printable(){
        @Override
        public int print(Graphics graphics, PageFormat pf, int pageIndex) throws PrinterException {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pf.getImageableX() * 2, pf.getImageableY() * 2);
            graphics2d.scale(0.5, 0.5);
            jLabel1.paint(graphics2d);

            return Printable.PAGE_EXISTS;
        }
    });
    
    boolean result = pj.printDialog();
    if (result) {
        try {
            pj.print();
        } catch (PrinterException printerException) {
            JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
        }
    }
}


}
